### ISSUE TITLE
complete the home page.

### ISSUE THREAD

**Issue by feitian124** [YunnuY/guitar#1]
1. 改变页眉和页脚的配色和背景图片，让他们看起来更专业。风格建议选择清新欢快的风格。
2. 请完善滚动图片部分，使其可以在上面显示字。参照 http://www.yupoo.com。请用合适的照片资源替代。
3. 完善首页其他部分，如文字描述。
   @tigerinfosys 负责完成。

**Comment by tigerinfosys** [comment]
Done.

**Comment by tigerinfosys** [comment]
Dynamic resource should be used instead of static resource. Need to make the change...
